# Use a Node.js base image

FROM node:18.14.2-alpine3.17

# Set the working directory inside the container  
WORKDIR /app  

# Copy package.json and package-lock.json to the container  
COPY package*.json ./  
 
#  # update npm
# RUN npm install -g npm@latest


# Install dependencies 
RUN npm ci

# Copy source code to container
COPY . .
# build nextjs app from package.json scripts
RUN npm run build

# Expose the port it will run on
EXPOSE 3000

# Start application using package.json scripts

CMD ["npm", "start"]