import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { format } from "path";
import { text } from "stream/consumers";
import { Button } from "react-bootstrap";
import getTodaysPrayers from "@/functions/getTodaysPrayers";
import getNextPrayer from "@/functions/getNextPrayer";
import next from "next";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // checkDate is used as a value to check if the currentDate has been changed
  const [checkDate, setCheckDate] = useState("");

  // add cron job to reexecute current date setup and useeffect setup, needs to run every 24 hours
  // update currentDate every 24 hours
  // in the same loop check if the formatted current date isnt the same
  var currentDate = new Date();
  var year = currentDate.getFullYear();
  var month = String(currentDate.getMonth() + 1).padStart(2, "0"); // Months are zero-based
  var day = String(currentDate.getDate()).padStart(2, "0");

  // Create the formatted date string to match api call date type
  const formattedDate = `${year}-${month}-${day}`;

  interface PrayerData {
    Asr: string;
    Dhuhr: string;
    Fajr: string;
    Isha: string;
    Maghrib: string;
  }
  // create the var which is the same structure as the response
  const [todaysPrayers, setTodaysPrayers] = useState<PrayerData>({
    Asr: "",
    Dhuhr: "",
    Fajr: "",
    Isha: "",
    Maghrib: "",
  });

  const [prayersLeftInDay, setPrayersLeftInDay] = useState<Record<
    string,
    string
  > | null>(null);
  // check if its first load, or the day has changed, if so call the API to get new results in todaysPrayers
  //TODO IMPORTANT need to update formattedDate daily/hourly to run this constantly
  useEffect(() => {
    const fetchData = async () => {
      if (formattedDate !== checkDate || checkDate == null) {
        setCheckDate(formattedDate);
        try {
          const result = await getTodaysPrayers(formattedDate);

          if (result) {
            setTodaysPrayers({
              Asr: "2023-12-14T14:35:00Z",
              Dhuhr: "2023-12-14T12:55:00Z",
              Fajr: "2023-12-14T06:54:00Z",
              Isha: "2023-12-14T20:27:00Z",
              Maghrib: "2023-12-14T16:59:00Z",
            });
          } else {
            console.log("Results undefined couldnt get todays prayers");
          }
        } catch (error) {
          console.error("Error fetching todays prayers", error);
        }
      }
    };
    fetchData();
  }, [formattedDate]);

  const [nextPrayerTime, setNextPrayerTime] = useState<Date | null>(null);
  const [nextPrayerName, setNextPrayerName] = useState<string | null>(null);

  // used in a use effect to trigger a rerun of the getNextPrayer function, it runs when the time passes that of the next prayer
  const [nextPrayerTimeActivator, setNextPrayerTimeActivator] = useState<
    number | null
  >(null);

  useEffect(() => {
    if (todaysPrayers != null) {
      const nextPrayer = getNextPrayer(todaysPrayers);
      if (nextPrayer) {
        setNextPrayerTime(new Date(nextPrayer.time));
        setNextPrayerName(nextPrayer.name);
      }
    }
  }, [todaysPrayers, nextPrayerTimeActivator]);

  // if a nextPrayerTime exists (should do after first load), start timer to see when it goes past nextPrayerTime
  //TODO CONTINUE FROM HERE - FIND OUT WHY HAVING THIS IN USE EFFECT CALLS THE TIMER LESS
  useEffect(() => {
    let intervalId: NodeJS.Timeout;

    if (nextPrayerTime && nextPrayerName) {
      // Pass a function reference, not an invocation
      intervalId = setInterval(
        () => updateNextPrayer(nextPrayerTime, nextPrayerName),
        5000
      );
    }

    // Cleanup function to clear the interval when the component unmounts
    return () => clearInterval(intervalId);
  }, [nextPrayerTime, nextPrayerName]);

  // if timer in this function goes past nextPrayerTime, it will know and will hit the activator which will rerun the useeffect to call a new prayer time
  function updateNextPrayer(nextPrayerTime: Date, nextPrayerName: string) {
    const timer = new Date();
    console.log("timer running...");
    if (timer > nextPrayerTime && nextPrayerName != "Isha") {
      setNextPrayerName("AFTER ISHA");
    } else if (timer > nextPrayerTime) {
      setNextPrayerTimeActivator(1);
    }
  }

  return (
    <>
      <Head>
        <title>The productive muslim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <p>
            {" "}
            {nextPrayerName}
            {String(nextPrayerTime)}
          </p>
        </div>
      </main>
    </>
  );
}
