apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpm-backend
  labels:
    app: tpm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpm-backend
  template:
    metadata:
      labels:
        app: tpm-backend
    spec:
      containers:
        - name: tpm-backend
          image: tpm-backend:0.0.1
          imagePullPolicy: Never
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: tpmsecrets
                  key: USER
            - name: CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: tpmsecrets
                  key: CONNECTION_NAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tpmsecrets
                  key: PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tpmsecrets
                  key: DB_NAME
            - name: VERIFICATION_EMAIL
              valueFrom:
                secretKeyRef:
                  name: tpmsecrets
                  key: VERIFICATION_EMAIL
            - name: VERIFICATION_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tpmsecrets
                  key: VERIFICATION_EMAIL_PASSWORD
          ports:
            - containerPort: 8080
              protocol: TCP
